In [1]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('framingham.csv')
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [3]:
df.shape

(4238, 16)

In [4]:
df_dropped = df.dropna(axis=0)
df=df_dropped
df.shape

(3656, 16)

In [5]:
X=df.drop(['TenYearCHD'],axis=1)
y=df['TenYearCHD']

In [6]:
X.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0  
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0  
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0  
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0  
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train.shape

(2924, 15)

In [9]:
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
sgd_clf = LogisticRegression(max_iter=3,C=100,solver='saga')
sgd_clf.fit(X_train, y_train)
sgd_clf.coef_[0]

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([ 5.95350461e-04,  8.35135725e-03, -2.87467604e-03, -2.73865552e-04,
        6.01175370e-03,  2.62426048e-04,  4.25630240e-05,  1.40568990e-03,
        3.11684527e-04, -4.79829408e-03,  1.27901193e-02, -1.27714210e-02,
       -7.94876340e-03, -2.42247280e-02,  3.46883189e-03])

In [10]:
y_pred = sgd_clf.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 85.11%


In [12]:
X_sl, _ , y_sl, _ = train_test_split(X, y, train_size=450, stratify=y, random_state=42)

In [13]:
X_sl.shape

(450, 15)

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X_sl,y_sl,test_size=0.2,stratify=y_sl,random_state=40)
X_train.to_csv('X_train1.csv', index=False)
X_test.to_csv('X_test1.csv', index=False)
y_train.to_csv('y_train1.csv', index=False)
y_test.to_csv('y_test1.csv', index=False)

In [15]:
X_train.shape

(360, 15)

In [16]:
sgd_clf = LogisticRegression(max_iter=3,C=100,solver='saga')
sgd_clf.fit(X_train, y_train)
sgd_clf.coef_[0]

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([ 8.21950996e-05,  2.40539619e-03, -3.00213007e-04, -1.90173221e-04,
       -1.91934741e-03,  6.05272728e-05,  2.55296101e-05,  3.23858640e-04,
       -4.57080608e-06, -4.18172229e-03,  6.76899878e-03, -1.05739569e-03,
       -1.16705265e-03, -7.38380213e-03, -4.95355735e-03])

In [17]:
y_pred = sgd_clf.predict(X_test)

In [18]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 84.44%


In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=3,C=100,solver='saga')
model.fit(X_train, y_train)
print(model.coef_[0])
y_pred=model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

[ 1.00736743e-04  2.84891446e-03 -4.34741110e-04 -2.02052920e-04
 -2.23322371e-03  5.73343204e-05  3.46178112e-05  3.67770624e-04
  2.44726604e-05 -6.99131473e-03  3.95903273e-03 -1.49253094e-03
 -1.85109213e-03 -8.37162086e-03  2.95270051e-03]
Accuracy: 84.44%


C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [20]:
X_sl2, _ , y_sl2, _ = train_test_split(X, y, train_size=850, stratify=y, random_state=42)

In [21]:
X_sl2.shape

(850, 15)

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X_sl2,y_sl2,test_size=0.2,stratify=y_sl2,random_state=40)
X_train.to_csv('X_train2.csv', index=False)
X_test.to_csv('X_test2.csv', index=False)
y_train.to_csv('y_train2.csv', index=False)
y_test.to_csv('y_test2.csv', index=False)

In [23]:
X_train.shape

(680, 15)

In [24]:
sgd_clf = LogisticRegression(max_iter=3,C=100,solver='saga')
sgd_clf.fit(X_train, y_train)
sgd_clf.coef_[0]

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([ 5.91781817e-04,  6.33514763e-03, -1.01947717e-03, -1.43995730e-05,
        1.85349155e-03,  8.51874003e-05,  1.78192814e-05,  4.07409394e-04,
        1.17663623e-05, -9.24820272e-03,  6.89998739e-03, -2.85411296e-03,
       -1.19900519e-03, -7.89574219e-03,  1.28294480e-04])

In [25]:
y_pred = sgd_clf.predict(X_test)

In [26]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 84.71%


In [27]:
X_sl3, _ , y_sl3, _ = train_test_split(X, y, train_size=1350, stratify=y, random_state=42)

In [28]:
X_sl3.shape

(1350, 15)

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X_sl3,y_sl3,test_size=0.2,stratify=y_sl3,random_state=40)
X_train.to_csv('X_train3.csv', index=False)
X_test.to_csv('X_test3.csv', index=False)
y_train.to_csv('y_train3.csv', index=False)
y_test.to_csv('y_test3.csv', index=False)

In [30]:
X_train.shape

(1080, 15)

In [31]:
sgd_clf = LogisticRegression(max_iter=3,C=100,solver='saga')
sgd_clf.fit(X_train, y_train)
sgd_clf.coef_[0]

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([ 7.94937732e-04,  1.09045695e-02, -2.20616367e-03, -2.44610223e-04,
        5.60523914e-03,  1.25448470e-04,  5.86868878e-05,  9.49439169e-04,
        2.13217773e-05, -6.87310882e-03,  1.11606252e-02, -5.76213374e-03,
       -4.15574469e-03, -1.96788021e-02, -3.20638099e-03])

In [32]:
y_pred = sgd_clf.predict(X_test)

In [33]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 84.81%
