In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import joblib
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
%matplotlib inline
plt.style.use('dark_background')

In [2]:
weights_paillier,bias_paillier,unenc_preds_paillier,cpu_seconds_paillier,cpu_usages_paillier,train_time_paillier,test_time_paillier=joblib.load('variables_paillier.pkl')

In [3]:
weights_ckks,bias_ckks,unenc_preds_ckks,cpu_seconds_ckks,cpu_usages_ckks,train_time_ckks,test_time_ckks=joblib.load('variables.pkl')

In [4]:
weights_sklearn,bias_sklearn,unenc_preds_sklearn=joblib.load('variables_sklearn.pkl')

In [5]:
y_test=pd.read_csv('y_test1.csv')
y_test=y_test.to_numpy()

In [6]:
y_test=y_test.reshape(-1,)
y_test

array([147.  ,  98.  ,  78.  , 190.  ,  57.  ,  74.  ,  40.  ,  89.  ,
       140.  ,  78.2 , 400.  ,  29.25,  57.  ,  60.8 ,  84.  , 115.  ,
        32.92,  26.  ,  83.  ,  80.  ,  79.  , 118.  ,  25.  ,  78.  ,
        59.  ,  63.  , 135.  ,  61.96,  78.57,  80.  ,  98.  , 146.  ,
       110.  , 253.  ,  95.  , 113.  ,  75.  , 130.  ,  28.34, 290.  ,
        40.  , 150.  , 200.  ,  61.25,  85.  , 145.  ,  70.  ,  35.  ,
       125.  , 107.  ,  55.  , 175.  , 110.  ,  81.  , 138.  ,  62.  ,
       140.  , 290.  ,  45.  ,  93.  , 400.  , 140.  , 106.  ,  77.  ,
        70.  , 280.  , 130.  , 300.  , 115.  , 120.  ,  79.  ,  39.  ,
        52.  , 101.  ,  69.  ,  55.  , 112.  , 116.  , 201.  ,  98.88,
       143.  , 102.  ,  85.  , 120.  ,  71.32, 211.  ,  95.  , 224.  ,
        34.65,  52.  ,  46.  , 125.  , 300.  ,  85.  ])

In [7]:
unenc_preds_paillier=np.array(unenc_preds_paillier)
unenc_preds_paillier.shape

(94,)

In [8]:
y_test.shape

(94,)

In [9]:
unenc_preds_ckks=np.array(unenc_preds_ckks)
unenc_preds_ckks=unenc_preds_ckks.reshape(-1,)
unenc_preds_ckks.shape

(94,)

In [10]:
unenc_preds_sklearn=unenc_preds_sklearn.reshape(-1,)
unenc_preds_sklearn.shape

(94,)

### Mean Squared Error:

In [11]:
from sklearn.metrics import mean_squared_error

In [12]:
mse_sklearn=mean_squared_error(unenc_preds_sklearn,y_test)

In [13]:
mse_sklearn

483.2575000879937

In [14]:
mse_ckks=mean_squared_error(unenc_preds_ckks,y_test)
mse_ckks

483.25722661564

In [15]:
mse_paillier=mean_squared_error(unenc_preds_paillier,y_test)
mse_paillier

483.2575000879934

In [16]:
def calculate_variance(numbers):
    
    if len(numbers) < 2:
        raise ValueError("Variance requires at least two data points.")
    
    mean = sum(numbers) / len(numbers)
    squared_diffs = [(x - mean) ** 2 for x in numbers]
    variance = sum(squared_diffs) / (len(numbers) - 1)
    
    return variance


print("Variance:", calculate_variance(unenc_preds_sklearn))
print("Variance:", calculate_variance(unenc_preds_ckks))
print("Variance:", calculate_variance(unenc_preds_paillier))

Variance: 4205.808056495047
Variance: 4205.809236641021
Variance: 4205.808056495053


In [17]:
f_statistic,p_value=stats.f_oneway(unenc_preds_sklearn,unenc_preds_ckks,unenc_preds_paillier)

In [18]:
f_statistic,p_value

(3.834973078755497e-12, 0.9999999999961591)

In [19]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference between the values")
else:
    print("There is no significant difference between the values")

There is no significant difference between the values


In [20]:
diff_between_ckks_and_sklearn=abs(unenc_preds_ckks-unenc_preds_sklearn)

In [21]:
diff_between_ckks_and_sklearn[:5]

array([3.16241325e-05, 2.10507042e-05, 2.09948554e-05, 3.60816738e-05,
       1.27099253e-05])

In [22]:
diff_between_paillier_and_sklearn=abs(unenc_preds_paillier-unenc_preds_sklearn)

In [23]:
diff_between_paillier_and_sklearn

array([5.68434189e-13, 8.66862138e-13, 7.67386155e-13, 1.42108547e-13,
       6.03961325e-13, 3.12638804e-13, 6.25277607e-13, 4.68958206e-13,
       4.97379915e-13, 1.84741111e-13, 1.13686838e-13, 5.96855898e-13,
       2.84217094e-14, 3.69482223e-13, 3.55271368e-13, 3.97903932e-13,
       6.03961325e-13, 1.66977543e-13, 1.84741111e-13, 1.84741111e-13,
       4.26325641e-13, 4.12114787e-13, 6.32383035e-13, 2.84217094e-13,
       3.41060513e-13, 2.48689958e-13, 4.40536496e-13, 4.12114787e-13,
       3.69482223e-13, 7.10542736e-13, 4.26325641e-13, 0.00000000e+00,
       3.55271368e-13, 2.84217094e-14, 1.70530257e-13, 4.83169060e-13,
       2.13162821e-13, 3.69482223e-13, 6.03961325e-13, 4.83169060e-13,
       6.60804744e-13, 3.97903932e-13, 5.68434189e-13, 5.82645043e-13,
       7.81597009e-13, 4.54747351e-13, 3.26849658e-13, 4.64517314e-13,
       4.68958206e-13, 4.12114787e-13, 2.13162821e-14, 0.00000000e+00,
       4.26325641e-13, 4.26325641e-13, 3.69482223e-13, 2.98427949e-13,
      

In [24]:
t_statistic,p_value=stats.ttest_ind(diff_between_paillier_and_sklearn,diff_between_ckks_and_sklearn)
t_statistic,p_value

(-24.144692103159898, 3.1719737318860307e-59)

In [25]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference between the ckks-sklearn preds and paillier-sklearn preds")
else:
    print("There is no significant difference between the ckks-sklearn preds and paillier-sklearn preds")

There is a significant difference between the ckks-sklearn preds and paillier-sklearn preds


In [26]:
l=len(diff_between_paillier_and_sklearn)

In [27]:
mse_ckks_with_sklearn=sum(diff_between_ckks_and_sklearn**2)/l
mse_ckks_with_sklearn

5.968797017879728e-10

In [28]:
mse_paillier_with_sklearn=sum(diff_between_paillier_and_sklearn**2)/l
mse_paillier_with_sklearn

2.0726572545249585e-25

### training time:

In [29]:
if train_time_ckks<train_time_paillier:
    print("ckks encryption takes less time to train the model")
else:
    print("paillier encryption takes less time to train the model")

ckks encryption takes less time to train the model


In [30]:
train_time_ckks

3.345334053039551

In [31]:
train_time_paillier

112.69778513908386

In [32]:
if test_time_ckks<test_time_paillier:
    print("ckks encrypted data takes less time to test the model")
else:
    print("paillier encrypted data takes less time to train the model")

ckks encrypted data takes less time to test the model


In [33]:
test_time_ckks

0.9361004829406738

In [34]:
test_time_paillier

4.70487642288208

In [35]:
joblib.dump(train_time_ckks,'train_time_ckks_375_5.pkl')
joblib.dump(train_time_paillier,'train_time_paillier_375_5.pkl')
joblib.dump(test_time_ckks,'test_time_ckks_375_5.pkl')
joblib.dump(test_time_paillier,'test_time_paillier_375_5.pkl')

['test_time_paillier_375_5.pkl']

### CPU % utilization:

In [36]:
def shortlist_cpu_usage(cpu):
    cpu_use=[]
    for i in cpu:
        if i>80:
            cpu_use.append(i)

    return cpu_use

In [37]:
paillier_cpu_use_short=shortlist_cpu_usage(cpu_usages_paillier)
paillier_cpu_use_short

[98.2,
 96.4,
 101.4,
 99.9,
 100.2,
 101.5,
 101.2,
 97.3,
 97.1,
 96.4,
 99.3,
 100.6,
 97.4,
 101.3,
 101.7,
 100.8,
 102.0,
 101.1,
 102.3,
 100.4,
 97.1,
 98.0,
 97.0,
 95.4,
 99.9,
 102.3,
 100.3,
 99.4,
 102.7,
 101.0,
 102.9,
 100.2,
 100.2,
 97.2,
 87.5,
 89.1,
 96.2,
 100.8,
 101.0,
 101.0,
 100.9,
 102.4,
 103.4,
 100.0,
 101.0,
 102.2,
 88.9,
 91.1,
 96.6,
 96.4,
 100.3,
 99.0,
 99.6,
 99.6,
 101.1,
 101.6,
 100.8,
 100.0,
 99.0,
 99.5,
 98.3,
 96.4,
 98.0,
 102.2,
 100.5,
 100.1,
 101.2,
 101.3,
 99.8,
 99.2,
 100.6,
 100.5,
 99.4,
 96.8,
 96.1,
 98.3,
 102.2,
 99.7,
 100.0,
 100.8,
 99.7,
 100.3,
 101.3,
 100.5,
 101.4,
 99.8,
 95.9,
 97.3,
 99.4,
 101.6,
 100.1,
 97.1,
 100.2,
 102.5,
 99.9,
 101.4,
 100.1,
 102.1,
 98.9,
 97.3,
 96.9,
 99.3,
 98.2,
 100.2,
 99.4,
 99.7,
 100.0,
 100.1]

In [38]:
paillier_cpu_use_short=np.array(paillier_cpu_use_short)

In [39]:
paillier_cpu_use_short.mean()

99.36203703703704

In [40]:
paillier_cpu_use_short.sum()

10731.1

In [41]:
cpu_seconds_for_paillier=paillier_cpu_use_short.sum()/100
cpu_seconds_for_paillier

107.311

In [42]:
paillier_cpu_use_short.max()

103.4

In [43]:
paillier_cpu_use_short.min()

87.5

In [44]:
len(paillier_cpu_use_short)

108

In [45]:
cpu_percent_consumption_paillier=(paillier_cpu_use_short.sum()/(108*200))*100

In [46]:
cpu_percent_consumption_paillier

49.68101851851852

In [47]:
ckks_cpu_use_short=shortlist_cpu_usage(cpu_usages_ckks)
ckks_cpu_use_short

[100.0, 95.4]

In [48]:
ckks_cpu_use_short=np.array(ckks_cpu_use_short)

In [49]:
ckks_cpu_use_short.mean()

97.7

In [50]:
ckks_cpu_use_short.sum()

195.4

In [51]:
cpu_seconds_for_ckks=ckks_cpu_use_short.sum()/100
cpu_seconds_for_ckks

1.954

In [52]:
ckks_cpu_use_short.max()

100.0

In [53]:
ckks_cpu_use_short.min()

95.4

In [54]:
len(ckks_cpu_use_short)

2

In [55]:
cpu_percent_consumption_ckks=(ckks_cpu_use_short.sum()/(2*200))*100
cpu_percent_consumption_ckks

48.85

In [56]:
joblib.dump((ckks_cpu_use_short.mean(),ckks_cpu_use_short.sum(),cpu_seconds_for_ckks,ckks_cpu_use_short.max(),ckks_cpu_use_short.min(),len(ckks_cpu_use_short),cpu_percent_consumption_ckks),'cpu_util_insights_ckks_375_5.pkl')

['cpu_util_insights_ckks_375_5.pkl']

In [57]:
joblib.dump((paillier_cpu_use_short.mean(),paillier_cpu_use_short.sum(),cpu_seconds_for_paillier,paillier_cpu_use_short.max(),paillier_cpu_use_short.min(),len(paillier_cpu_use_short),cpu_percent_consumption_paillier),'cpu_util_insights_paillier_375_5.pkl')

['cpu_util_insights_paillier_375_5.pkl']