In [1]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('framingham.csv')
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [3]:
df.shape

(4238, 16)

In [4]:
df_dropped = df.dropna(axis=0)
df=df_dropped
df.shape

(3656, 16)

In [5]:
X=df.drop(['TenYearCHD'],axis=1)
y=df['TenYearCHD']

In [6]:
X.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0  
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0  
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0  
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0  
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train.shape

(2924, 15)

In [9]:
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
sgd_clf = LogisticRegression(max_iter=3,C=100,solver='saga')
sgd_clf.fit(X_train, y_train)
sgd_clf.coef_[0]

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([ 5.13260719e-04,  8.30585790e-03, -2.56150211e-03, -1.61250486e-04,
        6.20618103e-03,  3.27877971e-04,  8.55766595e-05,  1.28788685e-03,
        2.63743826e-04, -3.85988890e-03,  1.16921440e-02, -1.30009476e-02,
       -8.98474110e-03, -2.40064345e-02,  3.66725731e-03])

In [10]:
y_pred = sgd_clf.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 85.11%


In [12]:
X_sl, _ , y_sl, _ = train_test_split(X, y, train_size=450, stratify=y, random_state=42)

In [13]:
X_sl.shape

(450, 15)

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X_sl,y_sl,test_size=0.2,stratify=y_sl,random_state=99)
X_train.to_csv('X_train1.csv', index=False)
X_test.to_csv('X_test1.csv', index=False)
y_train.to_csv('y_train1.csv', index=False)
y_test.to_csv('y_test1.csv', index=False)

In [15]:
X_train.shape

(360, 15)

In [16]:
sgd_clf = LogisticRegression(max_iter=3,C=100,solver='saga')
sgd_clf.fit(X_train, y_train)
sgd_clf.coef_[0]

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([ 2.20303530e-04,  2.90095479e-03,  8.02707772e-06, -5.52435417e-05,
       -7.10325214e-04,  2.21770490e-05,  3.71156344e-05,  2.47334953e-04,
        2.30187166e-06, -6.76799141e-03,  4.34845438e-03, -3.43944827e-04,
       -6.91582837e-04, -5.39119384e-03, -3.53978092e-03])

In [17]:
y_pred = sgd_clf.predict(X_test)

In [18]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 84.44%


In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=3,C=100,solver='saga')
model.fit(X_train, y_train)
print(model.coef_[0])
y_pred=model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

[ 4.62028095e-05  2.64140962e-03 -2.58713296e-04 -2.11215096e-04
 -2.92587999e-03  8.04375238e-05  5.36193180e-05  2.87956778e-04
 -1.37528835e-05 -7.25303893e-03  7.03128622e-03  6.99413489e-04
 -9.78982534e-04 -6.18445815e-03 -8.27913741e-03]
Accuracy: 84.44%


C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [20]:
X_sl2, _ , y_sl2, _ = train_test_split(X, y, train_size=850, stratify=y, random_state=42)

In [21]:
X_sl2.shape

(850, 15)

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X_sl2,y_sl2,test_size=0.2,stratify=y_sl2,random_state=99)
X_train.to_csv('X_train2.csv', index=False)
X_test.to_csv('X_test2.csv', index=False)
y_train.to_csv('y_train2.csv', index=False)
y_test.to_csv('y_test2.csv', index=False)

In [23]:
X_train.shape

(680, 15)

In [24]:
sgd_clf = LogisticRegression(max_iter=3,C=100,solver='saga')
sgd_clf.fit(X_train, y_train)
sgd_clf.coef_[0]

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([ 4.40309073e-04,  5.52993669e-03, -1.11284614e-03, -6.55421430e-05,
       -9.54469016e-04,  1.19537400e-04,  3.53942020e-05,  5.85397830e-04,
       -7.10917958e-06, -1.05214689e-02,  1.48049466e-02, -2.79603727e-04,
       -1.81186351e-03, -1.44634129e-02, -3.43105033e-03])

In [25]:
y_pred = sgd_clf.predict(X_test)

In [26]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 84.71%


In [27]:
X_sl3, _ , y_sl3, _ = train_test_split(X, y, train_size=1350, stratify=y, random_state=42)

In [28]:
X_sl3.shape

(1350, 15)

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X_sl3,y_sl3,test_size=0.2,stratify=y_sl3,random_state=99)
X_train.to_csv('X_train3.csv', index=False)
X_test.to_csv('X_test3.csv', index=False)
y_train.to_csv('y_train3.csv', index=False)
y_test.to_csv('y_test3.csv', index=False)

In [30]:
X_train.shape

(1080, 15)

In [31]:
sgd_clf = LogisticRegression(max_iter=3,C=100,solver='saga')
sgd_clf.fit(X_train, y_train)
sgd_clf.coef_[0]

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([ 6.13337597e-04,  6.24607735e-03, -2.15491162e-03, -1.00954208e-04,
        2.35221795e-03,  1.53881302e-04,  1.79717861e-05,  8.98413083e-04,
        6.06299601e-05, -5.15807120e-03,  8.23640498e-03, -4.38786408e-03,
       -2.63496566e-03, -1.74300336e-02, -1.69739054e-03])

In [32]:
y_pred = sgd_clf.predict(X_test)

In [33]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 84.81%
