In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import joblib
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
%matplotlib inline
plt.style.use('dark_background')

In [2]:
weights_paillier,bias_paillier,unenc_preds_paillier,cpu_seconds_paillier,cpu_usages_paillier,train_time_paillier,test_time_paillier=joblib.load('variables_paillier.pkl')

In [3]:
weights_ckks,bias_ckks,unenc_preds_ckks,cpu_seconds_ckks,cpu_usages_ckks,train_time_ckks,test_time_ckks=joblib.load('variables.pkl')

In [4]:
weights_sklearn,bias_sklearn,unenc_preds_sklearn=joblib.load('variables_sklearn.pkl')

In [5]:
y_test=pd.read_csv('y_test1.csv')
y_test=y_test.to_numpy()

In [6]:
y_test=y_test.reshape(-1,)
y_test

array([71.2, 75.1, 67.7, 71.3, 73.1, 55.3, 61.4, 74.1, 78.1, 76.8, 56.7,
       73. , 73.9, 69.1, 44.5, 68.9, 59.2, 58. , 72.5, 71.9, 69.4, 72.2,
       72.8, 75. , 75.9, 61.8, 76.5, 59.2, 52.4, 71.9, 59.5, 62.7, 71.6,
       62.2, 79.4, 74.5, 76. , 73.2, 51.2, 69. , 61.6, 69.9, 67.3, 83. ,
       67.7, 68. , 71.1, 74.8, 77.5, 73. , 75.3, 44.3, 73.6, 74.7, 75.5,
       77. , 57.5, 73.1, 74.8, 71. , 72.4, 67.1, 75. , 71.8, 45.4, 69.7,
       69.8, 76.2, 77.7, 69.6, 72. , 73.9, 73.2, 75. , 54.8, 74.2, 51. ,
       73.8, 68.1, 74.9, 61.1, 70. , 68.1, 64.2, 73.6, 71.9, 77. , 58.6])

In [7]:
unenc_preds_paillier=np.array(unenc_preds_paillier)
unenc_preds_paillier.shape

(88,)

In [8]:
y_test.shape

(88,)

In [9]:
unenc_preds_ckks=np.array(unenc_preds_ckks)
unenc_preds_ckks=unenc_preds_ckks.reshape(-1,)
unenc_preds_ckks.shape

(88,)

In [10]:
unenc_preds_sklearn=unenc_preds_sklearn.reshape(-1,)
unenc_preds_sklearn.shape

(88,)

### Mean Squared Error:

In [11]:
from sklearn.metrics import mean_squared_error

In [12]:
mse_sklearn=mean_squared_error(unenc_preds_sklearn,y_test)

In [13]:
mse_sklearn

15.941730074749175

In [14]:
mse_ckks=mean_squared_error(unenc_preds_ckks,y_test)
mse_ckks

15.942085679000519

In [15]:
mse_paillier=mean_squared_error(unenc_preds_paillier,y_test)
mse_paillier

15.941730077382886

In [16]:
def calculate_variance(numbers):
    
    if len(numbers) < 2:
        raise ValueError("Variance requires at least two data points.")
    
    mean = sum(numbers) / len(numbers)
    squared_diffs = [(x - mean) ** 2 for x in numbers]
    variance = sum(squared_diffs) / (len(numbers) - 1)
    
    return variance


print("Variance:", calculate_variance(unenc_preds_sklearn))
print("Variance:", calculate_variance(unenc_preds_ckks))
print("Variance:", calculate_variance(unenc_preds_paillier))

Variance: 72.00983219540083
Variance: 72.01003391651255
Variance: 72.00983219533472


In [17]:
f_statistic,p_value=stats.f_oneway(unenc_preds_sklearn,unenc_preds_ckks,unenc_preds_paillier)

In [18]:
f_statistic,p_value

(1.808309699282362e-09, 0.9999999981917015)

In [19]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference between the values")
else:
    print("There is no significant difference between the values")

There is no significant difference between the values


In [20]:
diff_between_ckks_and_sklearn=abs(unenc_preds_ckks-unenc_preds_sklearn)

In [21]:
diff_between_ckks_and_sklearn[:5]

array([4.73401784e-07, 3.01536189e-04, 1.78814123e-04, 2.10501110e-04,
       3.46785742e-05])

In [22]:
diff_between_paillier_and_sklearn=abs(unenc_preds_paillier-unenc_preds_sklearn)

In [23]:
diff_between_paillier_and_sklearn

array([5.38433653e-09, 5.32031663e-09, 5.34738831e-09, 5.41577094e-09,
       5.39118616e-09, 5.42222978e-09, 5.36979883e-09, 5.38491918e-09,
       5.36147127e-09, 5.31480282e-09, 5.41100320e-09, 5.35958122e-09,
       5.32857314e-09, 5.36978462e-09, 5.36949329e-09, 5.42331691e-09,
       5.27374766e-09, 5.36212497e-09, 5.41473355e-09, 5.38794609e-09,
       5.33901812e-09, 5.43641931e-09, 5.40245537e-09, 5.36323341e-09,
       5.37515632e-09, 5.37030331e-09, 5.30829425e-09, 5.37647793e-09,
       5.31024824e-09, 5.40114797e-09, 5.36984857e-09, 5.35524691e-09,
       5.41598411e-09, 5.35479217e-09, 5.41341194e-09, 5.34352296e-09,
       5.33687228e-09, 5.35204947e-09, 5.35786882e-09, 5.42985390e-09,
       5.37509948e-09, 5.48124035e-09, 5.37852429e-09, 5.38285860e-09,
       5.36296341e-09, 5.37468736e-09, 5.47727552e-09, 5.45632872e-09,
       5.34510036e-09, 5.41012923e-09, 5.35207789e-09, 5.36105205e-09,
       5.36262235e-09, 5.35440847e-09, 5.34866729e-09, 5.43711565e-09,
      

In [24]:
t_statistic,p_value=stats.ttest_ind(diff_between_paillier_and_sklearn,diff_between_ckks_and_sklearn)
t_statistic,p_value

(-14.890035302501778, 7.254421040702902e-33)

In [25]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference between the ckks-sklearn preds and paillier-sklearn preds")
else:
    print("There is no significant difference between the ckks-sklearn preds and paillier-sklearn preds")

There is a significant difference between the ckks-sklearn preds and paillier-sklearn preds


In [26]:
l=len(diff_between_paillier_and_sklearn)

In [27]:
mse_ckks_with_sklearn=sum(diff_between_ckks_and_sklearn**2)/l
mse_ckks_with_sklearn

6.273710880063194e-08

In [28]:
mse_paillier_with_sklearn=sum(diff_between_paillier_and_sklearn**2)/l
mse_paillier_with_sklearn

2.888613931335859e-17

### training time:

In [29]:
if train_time_ckks<train_time_paillier:
    print("ckks encryption takes less time to train the model")
else:
    print("paillier encryption takes less time to train the model")

ckks encryption takes less time to train the model


In [30]:
if test_time_ckks<test_time_paillier:
    print("ckks encrypted data takes less time to test the model")
else:
    print("paillier encrypted data takes less time to train the model")

ckks encrypted data takes less time to test the model


In [31]:
train_time_ckks

14.660992860794067

In [32]:
train_time_paillier

526.3637111186981

In [33]:
test_time_ckks

1.4419536590576172

In [34]:
test_time_paillier

12.408247947692871

In [35]:
joblib.dump(train_time_ckks,'train_time_ckks_348_12.pkl')
joblib.dump(train_time_paillier,'train_time_paillier_348_12.pkl')
joblib.dump(test_time_ckks,'test_time_ckks_348_12.pkl')
joblib.dump(test_time_paillier,'test_time_paillier_348_12.pkl')

['test_time_paillier_348_12.pkl']

### CPU % utilization:

In [36]:
def shortlist_cpu_usage(cpu):
    cpu_use=[]
    for i in cpu:
        if i>80:
            cpu_use.append(i)

    return cpu_use

In [37]:
paillier_cpu_use_short=shortlist_cpu_usage(cpu_usages_paillier)
paillier_cpu_use_short

[100.2,
 91.4,
 89.1,
 83.4,
 80.5,
 83.4,
 90.9,
 97.9,
 100.1,
 100.5,
 102.1,
 100.5,
 100.8,
 102.0,
 101.1,
 98.3,
 91.7,
 97.0,
 101.2,
 102.5,
 102.3,
 101.8,
 100.3,
 100.3,
 102.3,
 100.1,
 101.1,
 99.1,
 97.8,
 97.1,
 96.2,
 103.0,
 101.6,
 99.5,
 98.0,
 99.7,
 99.8,
 100.6,
 102.3,
 99.7,
 95.3,
 97.4,
 99.1,
 99.9,
 99.3,
 100.8,
 99.3,
 101.8,
 99.9,
 103.1,
 98.6,
 100.2,
 96.7,
 96.6,
 99.3,
 101.4,
 101.0,
 100.0,
 103.3,
 100.4,
 100.5,
 99.1,
 101.0,
 101.3,
 97.8,
 95.8,
 95.8,
 103.4,
 101.6,
 101.2,
 101.9,
 101.5,
 102.2,
 102.5,
 101.3,
 99.4,
 96.8,
 97.0,
 95.8,
 98.9,
 100.5,
 100.4,
 101.3,
 105.3,
 100.8,
 101.3,
 101.1,
 98.5,
 96.8,
 97.9,
 97.0,
 100.1,
 101.9,
 102.0,
 99.5,
 94.5,
 100.3,
 98.8,
 100.6,
 99.2,
 98.7,
 97.8,
 97.1,
 99.0,
 100.1,
 101.3,
 101.7,
 99.0,
 97.8,
 102.7,
 101.3,
 100.6,
 96.7,
 97.0,
 98.1,
 100.6,
 101.4,
 100.3,
 102.5,
 99.2,
 96.7,
 103.8,
 98.8,
 99.8,
 98.5,
 99.0,
 95.5,
 98.9,
 99.7,
 100.5,
 100.2,
 103.7,
 98.9,
 1

In [38]:
paillier_cpu_use_short=np.array(paillier_cpu_use_short)

In [39]:
paillier_cpu_use_short.mean()

99.47591093117408

In [40]:
paillier_cpu_use_short.sum()

49141.1

In [41]:
cpu_seconds_for_paillier=paillier_cpu_use_short.sum()/100
cpu_seconds_for_paillier

491.411

In [42]:
paillier_cpu_use_short.max()

126.2

In [43]:
paillier_cpu_use_short.min()

80.5

In [44]:
len(paillier_cpu_use_short)

494

In [45]:
cpu_percent_consumption_paillier=(paillier_cpu_use_short.sum()/(len(paillier_cpu_use_short)*200))*100

In [46]:
cpu_percent_consumption_paillier

49.73795546558704

In [47]:
ckks_cpu_use_short=shortlist_cpu_usage(cpu_usages_ckks)
ckks_cpu_use_short

[99.6, 99.7, 91.5, 96.2, 96.4, 99.0, 95.7, 103.6, 99.3, 107.1, 109.5]

In [48]:
ckks_cpu_use_short=np.array(ckks_cpu_use_short)

In [49]:
ckks_cpu_use_short.mean()

99.78181818181817

In [50]:
ckks_cpu_use_short.sum()

1097.6

In [51]:
cpu_seconds_for_ckks=ckks_cpu_use_short.sum()/100
cpu_seconds_for_ckks

10.975999999999999

In [52]:
ckks_cpu_use_short.max()

109.5

In [53]:
ckks_cpu_use_short.min()

91.5

In [54]:
len(ckks_cpu_use_short)

11

In [55]:
cpu_percent_consumption_ckks=(ckks_cpu_use_short.sum()/(len(ckks_cpu_use_short)*200))*100
cpu_percent_consumption_ckks

49.89090909090908

In [56]:
joblib.dump((ckks_cpu_use_short.mean(),ckks_cpu_use_short.sum(),cpu_seconds_for_ckks,ckks_cpu_use_short.max(),ckks_cpu_use_short.min(),len(ckks_cpu_use_short),cpu_percent_consumption_ckks),'cpu_util_insights_ckks_348_12.pkl')

['cpu_util_insights_ckks_348_12.pkl']

In [57]:
joblib.dump((paillier_cpu_use_short.mean(),paillier_cpu_use_short.sum(),cpu_seconds_for_paillier,paillier_cpu_use_short.max(),paillier_cpu_use_short.min(),len(paillier_cpu_use_short),cpu_percent_consumption_paillier),'cpu_util_insights_paillier_348_12.pkl')

['cpu_util_insights_paillier_348_12.pkl']