In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import joblib
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
%matplotlib inline
plt.style.use('dark_background')

In [2]:
weights_paillier,bias_paillier,unenc_preds_paillier,cpu_seconds_paillier,cpu_usages_paillier,train_time_paillier,test_time_paillier=joblib.load('variables_paillier.pkl')

In [3]:
weights_ckks,bias_ckks,unenc_preds_ckks,cpu_seconds_ckks,cpu_usages_ckks,train_time_ckks,test_time_ckks=joblib.load('variables.pkl')

In [4]:
weights_sklearn,bias_sklearn,unenc_preds_sklearn=joblib.load('variables_sklearn.pkl')

In [5]:
y_test=pd.read_csv('y_test2.csv')
y_test=y_test.to_numpy()

In [6]:
y_test=y_test.reshape(-1,)
y_test

array([65.8, 76.6, 65.7, 72.6, 72.1, 59.3, 74.7, 72.1, 73.9, 75.5, 77.8,
       74.4, 67.3, 44.6, 72.6, 88. , 73. , 72.3, 72. , 81. , 73. , 69.5,
       66.5, 64.5, 68.3, 57.8, 73.2, 72. , 54.1, 73.8, 65. , 64. , 70. ,
       54.3, 68.1, 73.9, 63. , 72.1, 58.4, 50. , 75.5, 44.5, 48.2, 82. ,
       74.6, 71.1, 53.6, 45.1, 78.9, 55. , 73.6, 77.3, 69.6, 73. , 54.9,
       75.8, 57.9, 74.4, 67.6, 58. , 69.5, 57.3, 76.5, 72.3, 51.7, 76. ,
       66.1, 57.5, 69.1, 74.6, 74.3, 68.1, 59.5, 74.5, 71. , 67.8, 51.4,
       78.5, 59.9, 44.8, 75. , 71.2, 73.7, 66.7, 74.5, 58. , 68. , 65.4,
       64.4, 76. , 63.4, 68.2, 74. , 68.1, 73.6, 88. , 62.4, 68.8, 64.1,
       71. , 76.1, 71.2, 71.9, 75.3, 76.2, 73.6, 62.8, 74.1, 72.9, 77.6,
       71. , 81.2, 50. , 75.4, 45.9, 75.5, 72. , 72.6, 78.3, 78.7, 52. ,
       53.4, 56.7, 78.8, 72.5, 81.4, 72.8, 74.3, 56.5, 83. , 76.8, 73.7,
       59.2, 46.6, 45.4, 47.8, 78. , 56.5, 65.8, 74.6, 52.9, 72.4, 74.8,
       64.7, 68.7, 79.4, 71.7, 71.6, 81.3, 75.7, 71

In [7]:
unenc_preds_paillier=np.array(unenc_preds_paillier)
unenc_preds_paillier.shape

(160,)

In [8]:
y_test.shape

(160,)

In [9]:
unenc_preds_ckks=np.array(unenc_preds_ckks)
unenc_preds_ckks=unenc_preds_ckks.reshape(-1,)
unenc_preds_ckks.shape

(160,)

In [10]:
unenc_preds_sklearn=unenc_preds_sklearn.reshape(-1,)
unenc_preds_sklearn.shape

(160,)

### Mean Squared Error:

In [11]:
from sklearn.metrics import mean_squared_error

In [12]:
mse_sklearn=mean_squared_error(unenc_preds_sklearn,y_test)

In [13]:
mse_sklearn

10.549915956551716

In [14]:
mse_ckks=mean_squared_error(unenc_preds_ckks,y_test)
mse_ckks

10.549850429000896

In [15]:
mse_paillier=mean_squared_error(unenc_preds_paillier,y_test)
mse_paillier

10.549915956509903

In [16]:
def calculate_variance(numbers):
    
    if len(numbers) < 2:
        raise ValueError("Variance requires at least two data points.")
    
    mean = sum(numbers) / len(numbers)
    squared_diffs = [(x - mean) ** 2 for x in numbers]
    variance = sum(squared_diffs) / (len(numbers) - 1)
    
    return variance


print("Variance:", calculate_variance(unenc_preds_sklearn))
print("Variance:", calculate_variance(unenc_preds_ckks))
print("Variance:", calculate_variance(unenc_preds_paillier))

Variance: 79.96704340535386
Variance: 79.96653458602908
Variance: 79.96704340549988


In [17]:
f_statistic,p_value=stats.f_oneway(unenc_preds_sklearn,unenc_preds_ckks,unenc_preds_paillier)

In [18]:
f_statistic,p_value

(6.823239294145828e-12, 0.9999999999931685)

In [19]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference between the values")
else:
    print("There is no significant difference between the values")

There is no significant difference between the values


In [20]:
diff_between_ckks_and_sklearn=abs(unenc_preds_ckks-unenc_preds_sklearn)

In [21]:
diff_between_ckks_and_sklearn[:5]

array([2.66795391e-04, 3.11355909e-04, 2.50234433e-05, 2.57842389e-04,
       1.88435981e-04])

In [22]:
diff_between_paillier_and_sklearn=abs(unenc_preds_paillier-unenc_preds_sklearn)

In [23]:
diff_between_paillier_and_sklearn

array([3.03333536e-09, 3.09722736e-09, 3.01126590e-09, 2.90037860e-09,
       3.08571657e-09, 3.05081471e-09, 2.99310443e-09, 3.09482573e-09,
       3.05254844e-09, 3.02107139e-09, 2.96653013e-09, 2.97346503e-09,
       3.17561444e-09, 3.17756133e-09, 2.87816704e-09, 3.01447756e-09,
       3.07211678e-09, 2.97413294e-09, 2.98135205e-09, 3.17524496e-09,
       3.11099768e-09, 2.94942026e-09, 3.11912629e-09, 3.08845927e-09,
       3.19963078e-09, 3.14693693e-09, 3.01820080e-09, 3.02595993e-09,
       3.11711545e-09, 3.12341797e-09, 3.09474046e-09, 3.09935899e-09,
       2.90832247e-09, 3.10259907e-09, 3.01764658e-09, 2.95359825e-09,
       3.03501224e-09, 3.09300674e-09, 3.22113181e-09, 3.19682414e-09,
       3.09213988e-09, 3.16035198e-09, 3.20208215e-09, 3.20241611e-09,
       3.13761461e-09, 3.12431325e-09, 3.10038217e-09, 3.07939274e-09,
       2.98840064e-09, 3.16889270e-09, 3.11618464e-09, 3.12090265e-09,
       3.07824166e-09, 2.94632230e-09, 3.20319060e-09, 3.09495363e-09,
      

In [24]:
t_statistic,p_value=stats.ttest_ind(diff_between_paillier_and_sklearn,diff_between_ckks_and_sklearn)
t_statistic,p_value

(-18.003171056769364, 1.8753594353010618e-50)

In [25]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference between the ckks-sklearn preds and paillier-sklearn preds")
else:
    print("There is no significant difference between the ckks-sklearn preds and paillier-sklearn preds")

There is a significant difference between the ckks-sklearn preds and paillier-sklearn preds


In [26]:
l=len(diff_between_paillier_and_sklearn)

In [27]:
mse_ckks_with_sklearn=sum(diff_between_ckks_and_sklearn**2)/l
mse_ckks_with_sklearn

3.2446481775136085e-08

In [28]:
mse_paillier_with_sklearn=sum(diff_between_paillier_and_sklearn**2)/l
mse_paillier_with_sklearn

9.442173575245906e-18

### training time:

In [29]:
if train_time_ckks<train_time_paillier:
    print("ckks encryption takes less time to train the model")
else:
    print("paillier encryption takes less time to train the model")

ckks encryption takes less time to train the model


In [30]:
if test_time_ckks<test_time_paillier:
    print("ckks encrypted data takes less time to test the model")
else:
    print("paillier encrypted data takes less time to train the model")

ckks encrypted data takes less time to test the model


In [31]:
train_time_ckks

25.35484480857849

In [32]:
train_time_paillier

2674.7212731838226

In [33]:
test_time_ckks

3.3370614051818848

In [34]:
test_time_paillier

44.56397771835327

In [35]:
joblib.dump(train_time_ckks,'train_time_ckks_640_21.pkl')
joblib.dump(train_time_paillier,'train_time_paillier_640_21.pkl')
joblib.dump(test_time_ckks,'test_time_ckks_640_21.pkl')
joblib.dump(test_time_paillier,'test_time_paillier_640_21.pkl')

['test_time_paillier_640_21.pkl']

### CPU % utilization:

In [36]:
def shortlist_cpu_usage(cpu):
    cpu_use=[]
    for i in cpu:
        if i>80:
            cpu_use.append(i)

    return cpu_use

In [37]:
paillier_cpu_use_short=shortlist_cpu_usage(cpu_usages_paillier)
paillier_cpu_use_short

[81.2,
 90.3,
 88.3,
 94.9,
 98.3,
 99.8,
 101.1,
 102.2,
 96.9,
 97.9,
 101.4,
 101.4,
 98.7,
 95.9,
 95.4,
 97.3,
 100.4,
 100.1,
 99.4,
 101.5,
 102.6,
 102.7,
 99.9,
 101.1,
 102.0,
 99.1,
 97.1,
 96.3,
 97.7,
 100.0,
 100.1,
 98.3,
 101.3,
 100.8,
 102.6,
 99.3,
 102.6,
 102.8,
 97.9,
 97.4,
 94.4,
 98.4,
 98.6,
 101.3,
 99.0,
 103.6,
 103.7,
 100.2,
 103.1,
 100.1,
 98.3,
 95.1,
 93.6,
 101.5,
 102.1,
 99.9,
 101.9,
 99.1,
 100.8,
 101.4,
 100.7,
 101.7,
 100.2,
 98.4,
 96.9,
 94.4,
 101.9,
 98.8,
 102.0,
 100.1,
 102.8,
 101.6,
 101.7,
 101.7,
 102.9,
 98.5,
 97.9,
 96.4,
 97.6,
 99.3,
 103.8,
 100.1,
 99.8,
 102.3,
 99.1,
 103.0,
 101.2,
 101.9,
 99.2,
 95.7,
 95.8,
 100.3,
 98.8,
 97.8,
 100.6,
 99.7,
 99.3,
 99.7,
 103.0,
 101.0,
 102.9,
 98.2,
 96.2,
 97.2,
 99.8,
 100.2,
 101.1,
 101.4,
 101.1,
 100.6,
 100.9,
 102.9,
 100.0,
 103.3,
 98.4,
 96.4,
 97.2,
 99.0,
 99.3,
 102.9,
 100.4,
 98.0,
 100.2,
 102.3,
 101.9,
 100.7,
 100.2,
 98.4,
 95.6,
 95.8,
 100.2,
 101.0,
 101.9,

In [38]:
paillier_cpu_use_short=np.array(paillier_cpu_use_short)

In [39]:
paillier_cpu_use_short.mean()

99.47836349331236

In [40]:
paillier_cpu_use_short.sum()

252874.0

In [41]:
cpu_seconds_for_paillier=paillier_cpu_use_short.sum()/100
cpu_seconds_for_paillier

2528.74

In [42]:
paillier_cpu_use_short.max()

115.2

In [43]:
paillier_cpu_use_short.min()

81.2

In [44]:
len(paillier_cpu_use_short)

2542

In [45]:
cpu_percent_consumption_paillier=(paillier_cpu_use_short.sum()/(len(paillier_cpu_use_short)*200))*100

In [46]:
cpu_percent_consumption_paillier

49.73918174665617

In [47]:
ckks_cpu_use_short=shortlist_cpu_usage(cpu_usages_ckks)
ckks_cpu_use_short

[111.8,
 104.3,
 100.2,
 113.2,
 84.2,
 95.5,
 95.2,
 107.4,
 96.7,
 100.3,
 100.1,
 108.1,
 112.6,
 103.8,
 112.9,
 96.4,
 97.6,
 97.5,
 98.2,
 104.8,
 94.8]

In [48]:
ckks_cpu_use_short=np.array(ckks_cpu_use_short)

In [49]:
ckks_cpu_use_short.mean()

101.6952380952381

In [50]:
ckks_cpu_use_short.sum()

2135.6

In [51]:
cpu_seconds_for_ckks=ckks_cpu_use_short.sum()/100
cpu_seconds_for_ckks

21.355999999999998

In [52]:
ckks_cpu_use_short.max()

113.2

In [53]:
ckks_cpu_use_short.min()

84.2

In [54]:
len(ckks_cpu_use_short)

21

In [55]:
cpu_percent_consumption_ckks=(ckks_cpu_use_short.sum()/(len(ckks_cpu_use_short)*200))*100
cpu_percent_consumption_ckks

50.84761904761904

In [56]:
joblib.dump((ckks_cpu_use_short.mean(),ckks_cpu_use_short.sum(),cpu_seconds_for_ckks,ckks_cpu_use_short.max(),ckks_cpu_use_short.min(),len(ckks_cpu_use_short),cpu_percent_consumption_ckks),'cpu_util_insights_ckks_640_21.pkl')

['cpu_util_insights_ckks_640_21.pkl']

In [57]:
joblib.dump((paillier_cpu_use_short.mean(),paillier_cpu_use_short.sum(),cpu_seconds_for_paillier,paillier_cpu_use_short.max(),paillier_cpu_use_short.min(),len(paillier_cpu_use_short),cpu_percent_consumption_paillier),'cpu_util_insights_paillier_640_21.pkl')

['cpu_util_insights_paillier_640_21.pkl']