In [1]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('framingham.csv')
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [3]:
df.shape

(4238, 16)

In [4]:
df_dropped = df.dropna(axis=0)
df=df_dropped
df.shape

(3656, 16)

In [5]:
X=df.drop(['TenYearCHD'],axis=1)
y=df['TenYearCHD']

In [6]:
X.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0  
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0  
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0  
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0  
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train.shape

(2924, 15)

In [9]:
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
sgd_clf = LogisticRegression(max_iter=3,C=100,solver='saga')
sgd_clf.fit(X_train, y_train)
sgd_clf.coef_[0]

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([ 5.76424690e-04,  7.40436398e-03, -2.69110196e-03, -2.84935650e-04,
        2.83949010e-03,  2.92354615e-04,  9.99124158e-05,  1.40544904e-03,
        2.65417060e-04, -3.93639203e-03,  1.29654240e-02, -1.34571564e-02,
       -8.97183893e-03, -2.43503944e-02,  3.09978232e-03])

In [10]:
y_pred = sgd_clf.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 85.11%


In [12]:
X_sl, _ , y_sl, _ = train_test_split(X, y, train_size=450, stratify=y, random_state=42)

In [13]:
X_sl.shape

(450, 15)

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X_sl,y_sl,test_size=0.2,stratify=y_sl,random_state=23)
X_train.to_csv('X_train1.csv', index=False)
X_test.to_csv('X_test1.csv', index=False)
y_train.to_csv('y_train1.csv', index=False)
y_test.to_csv('y_test1.csv', index=False)

In [15]:
X_train.shape

(360, 15)

In [16]:
sgd_clf = LogisticRegression(max_iter=3,C=100,solver='saga')
sgd_clf.fit(X_train, y_train)
sgd_clf.coef_[0]

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([ 1.84290759e-04,  2.26052031e-03, -4.83725141e-04,  6.19566632e-06,
        1.10184004e-03,  9.84489192e-05,  2.89964216e-05,  3.55743189e-04,
        3.56502796e-05, -9.76094657e-03,  7.69053373e-03, -1.61215394e-03,
       -2.13043056e-03, -9.29347625e-03,  2.66728711e-03])

In [17]:
y_pred = sgd_clf.predict(X_test)

In [18]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 84.44%


In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=3,C=100,solver='saga')
model.fit(X_train, y_train)
print(model.coef_[0])
y_pred=model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

[ 1.61975234e-04  1.51008677e-03 -3.79691125e-04  2.76842853e-05
  2.84137149e-03  8.24242366e-05  2.86587286e-05  2.75148529e-04
  1.35999753e-05 -8.85009936e-03  6.20589764e-03  3.75926761e-04
 -1.55431220e-03 -6.54350076e-03  1.50765159e-03]
Accuracy: 84.44%


C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [20]:
X_sl2, _ , y_sl2, _ = train_test_split(X, y, train_size=850, stratify=y, random_state=42)

In [21]:
X_sl2.shape

(850, 15)

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X_sl2,y_sl2,test_size=0.2,stratify=y_sl2,random_state=80)
X_train.to_csv('X_train2.csv', index=False)
X_test.to_csv('X_test2.csv', index=False)
y_train.to_csv('y_train2.csv', index=False)
y_test.to_csv('y_test2.csv', index=False)

In [23]:
X_train.shape

(680, 15)

In [24]:
sgd_clf = LogisticRegression(max_iter=3,C=100,solver='saga')
sgd_clf.fit(X_train, y_train)
sgd_clf.coef_[0]

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([ 4.35448417e-04,  5.67847688e-03, -5.27931578e-04, -1.08450825e-04,
        1.20073889e-03,  1.96929366e-05, -7.40901100e-06,  4.54105816e-04,
        7.59875241e-06, -9.35221188e-03,  7.20135211e-03, -4.44275679e-03,
       -1.85293480e-03, -1.15501380e-02,  3.99566956e-03])

In [25]:
y_pred = sgd_clf.predict(X_test)

In [26]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 84.71%


In [27]:
X_sl3, _ , y_sl3, _ = train_test_split(X, y, train_size=1350, stratify=y, random_state=42)

In [28]:
X_sl3.shape

(1350, 15)

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X_sl3,y_sl3,test_size=0.2,stratify=y_sl3,random_state=80)
X_train.to_csv('X_train3.csv', index=False)
X_test.to_csv('X_test3.csv', index=False)
y_train.to_csv('y_train3.csv', index=False)
y_test.to_csv('y_test3.csv', index=False)

In [30]:
X_train.shape

(1080, 15)

In [31]:
sgd_clf = LogisticRegression(max_iter=3,C=100,solver='saga')
sgd_clf.fit(X_train, y_train)
sgd_clf.coef_[0]

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


array([ 5.24525947e-04,  7.81960402e-03, -1.63471517e-03,  6.61448293e-05,
        7.96336676e-03,  2.77288551e-05,  8.06484506e-05,  8.81248908e-04,
        1.47967349e-04, -7.18068942e-03,  9.37240596e-03, -3.56480522e-03,
       -2.82089801e-03, -1.53957322e-02, -2.85983094e-03])

In [32]:
y_pred = sgd_clf.predict(X_test)

In [33]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 84.81%
