In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import joblib
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
%matplotlib inline
plt.style.use('dark_background')

In [2]:
weights_paillier,bias_paillier,unenc_preds_paillier,cpu_seconds_paillier,cpu_usages_paillier,train_time_paillier,test_time_paillier=joblib.load('variables_paillier.pkl')

In [3]:
weights_ckks,bias_ckks,unenc_preds_ckks,cpu_seconds_ckks,cpu_usages_ckks,train_time_ckks,test_time_ckks=joblib.load('variables.pkl')

In [4]:
weights_sklearn,bias_sklearn,unenc_preds_sklearn=joblib.load('variables_sklearn.pkl')

In [5]:
y_test=pd.read_csv('y_test3.csv')
y_test=y_test.to_numpy()

In [6]:
y_test=y_test.reshape(-1,)
y_test

array([71. , 69.9, 69.3, 74.5, 57.4, 64.2, 74.1, 57.9, 56.7, 74.2, 77.3,
       72.9, 71. , 75.5, 65.9, 72. , 72.4, 73. , 72. , 65.9, 59.2, 58.1,
       72.1, 58.5, 59.1, 75.4, 65.6, 71.3, 73.2, 58.8, 72.3, 72.4, 73.3,
       73.5, 69.6, 81.7, 72. , 66.1, 59.7, 52.8, 78.7, 58.4, 73.5, 84. ,
       71. , 55.8, 89. , 73.9, 59.7, 88. , 73. , 72.4, 69.3, 45.4, 58.9,
       69.4, 77.6, 65.3, 53.6, 61.4, 68.3, 71.6, 75. , 71.8, 68. , 82. ,
       81.7, 74. , 69.2, 69.6, 68.4, 66.8, 62.1, 54.3, 58.4, 65.3, 75.5,
       62.5, 61.2, 46.2, 69.1, 75.4, 81.5, 51.6, 72.8, 69.5, 66. , 74.5,
       76.2, 65.8, 69. , 75.6, 78. , 76.5, 76. , 52.6, 74.6, 78.9, 62.2,
       76.7, 76. , 62.2, 72.9, 62.5, 71.7, 63. , 65.4, 69.3, 79. , 50. ,
       71. , 73.7, 69.7, 78.6, 48.2, 73.5, 74.1, 62.7, 72.5, 81.4, 71.4,
       59.5, 55. , 67.6, 67. , 46.7, 75.2, 83. , 73. , 67.5, 72.6, 67.7,
       65.9, 75. , 89. , 73. , 75.8, 44.5, 69.5, 47.1, 59. , 58.2, 69.2,
       77.8, 69.9, 74. , 71.7, 56.8, 57.5, 53.4, 87

In [7]:
unenc_preds_paillier=np.array(unenc_preds_paillier)
unenc_preds_paillier.shape

(264,)

In [8]:
y_test.shape

(264,)

In [9]:
unenc_preds_ckks=np.array(unenc_preds_ckks)
unenc_preds_ckks=unenc_preds_ckks.reshape(-1,)
unenc_preds_ckks.shape

(264,)

In [10]:
unenc_preds_sklearn=unenc_preds_sklearn.reshape(-1,)
unenc_preds_sklearn.shape

(264,)

### Mean Squared Error:

In [11]:
from sklearn.metrics import mean_squared_error

In [12]:
mse_sklearn=mean_squared_error(unenc_preds_sklearn,y_test)

In [13]:
mse_sklearn

13.725901006918571

In [14]:
mse_ckks=mean_squared_error(unenc_preds_ckks,y_test)
mse_ckks

13.725916472004684

In [15]:
mse_paillier=mean_squared_error(unenc_preds_paillier,y_test)
mse_paillier

13.725901008411283

In [16]:
def calculate_variance(numbers):
    
    if len(numbers) < 2:
        raise ValueError("Variance requires at least two data points.")
    
    mean = sum(numbers) / len(numbers)
    squared_diffs = [(x - mean) ** 2 for x in numbers]
    variance = sum(squared_diffs) / (len(numbers) - 1)
    
    return variance


print("Variance:", calculate_variance(unenc_preds_sklearn))
print("Variance:", calculate_variance(unenc_preds_ckks))
print("Variance:", calculate_variance(unenc_preds_paillier))

Variance: 70.71505975489042
Variance: 70.71512294809148
Variance: 70.71505975470016


In [17]:
f_statistic,p_value=stats.f_oneway(unenc_preds_sklearn,unenc_preds_ckks,unenc_preds_paillier)

In [18]:
f_statistic,p_value

(1.076358483273022e-09, 0.9999999989236569)

In [19]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference between the values")
else:
    print("There is no significant difference between the values")

There is no significant difference between the values


In [20]:
diff_between_ckks_and_sklearn=abs(unenc_preds_ckks-unenc_preds_sklearn)

In [21]:
diff_between_ckks_and_sklearn[:5]

array([1.50867876e-04, 1.11441597e-04, 1.07775314e-04, 3.32576252e-05,
       3.32202717e-07])

In [22]:
diff_between_paillier_and_sklearn=abs(unenc_preds_paillier-unenc_preds_sklearn)

In [23]:
diff_between_paillier_and_sklearn

array([2.87703017e-09, 2.94511437e-09, 3.07191783e-09, 3.08641290e-09,
       3.14203419e-09, 3.01423597e-09, 2.91446156e-09, 2.96144265e-09,
       3.11847259e-09, 3.04012815e-09, 3.19612070e-09, 2.94912184e-09,
       3.11261772e-09, 2.97606562e-09, 3.11352721e-09, 3.16704529e-09,
       3.08617132e-09, 3.14818749e-09, 2.91002777e-09, 3.13889359e-09,
       3.07580450e-09, 2.91456104e-09, 3.08979509e-09, 2.91501578e-09,
       2.95892022e-09, 3.28751071e-09, 3.18792104e-09, 3.21379900e-09,
       3.12618909e-09, 3.08789083e-09, 2.88976310e-09, 3.00326519e-09,
       2.98322789e-09, 2.94924973e-09, 3.20477511e-09, 3.02306091e-09,
       3.03951708e-09, 3.09434256e-09, 2.96913072e-09, 2.99178993e-09,
       2.96519431e-09, 3.17442783e-09, 3.02745207e-09, 3.12873283e-09,
       2.94680547e-09, 2.87723623e-09, 3.10875237e-09, 3.11358406e-09,
       3.04534353e-09, 3.15372972e-09, 2.90994251e-09, 3.06231129e-09,
       3.02294723e-09, 3.18176063e-09, 2.95144531e-09, 3.03421643e-09,
      

In [24]:
t_statistic,p_value=stats.ttest_ind(diff_between_paillier_and_sklearn,diff_between_ckks_and_sklearn)
t_statistic,p_value

(-22.69889720342139, 4.9723513455630665e-80)

In [25]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference between the ckks-sklearn preds and paillier-sklearn preds")
else:
    print("There is no significant difference between the ckks-sklearn preds and paillier-sklearn preds")

There is a significant difference between the ckks-sklearn preds and paillier-sklearn preds


In [58]:
t_statistic,p_value=stats.ttest_ind(unenc_preds_paillier,unenc_preds_ckks)
t_statistic,p_value

(4.017921727497884e-05, 0.9999679568561215)

In [60]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference")
else:
    print("There is no significant difference between")

There is no significant difference between


In [26]:
l=len(diff_between_paillier_and_sklearn)

In [27]:
mse_ckks_with_sklearn=sum(diff_between_ckks_and_sklearn**2)/l
mse_ckks_with_sklearn

5.386691567473854e-09

In [28]:
mse_paillier_with_sklearn=sum(diff_between_paillier_and_sklearn**2)/l
mse_paillier_with_sklearn

9.370359458199681e-18

### training time:

In [29]:
if train_time_ckks<train_time_paillier:
    print("ckks encryption takes less time to train the model")
else:
    print("paillier encryption takes less time to train the model")

ckks encryption takes less time to train the model


In [30]:
if test_time_ckks<test_time_paillier:
    print("ckks encrypted data takes less time to test the model")
else:
    print("paillier encrypted data takes less time to train the model")

ckks encrypted data takes less time to test the model


In [31]:
train_time_ckks

32.76336717605591

In [32]:
train_time_paillier

4395.700360059738

In [33]:
test_time_ckks

5.7867302894592285

In [34]:
test_time_paillier

72.91429567337036

In [35]:
joblib.dump(train_time_ckks,'train_time_ckks_1055_21.pkl')
joblib.dump(train_time_paillier,'train_time_paillier_1055_21.pkl')
joblib.dump(test_time_ckks,'test_time_ckks_1055_21.pkl')
joblib.dump(test_time_paillier,'test_time_paillier_1055_21.pkl')

['test_time_paillier_1055_21.pkl']

### CPU % utilization:

In [36]:
def shortlist_cpu_usage(cpu):
    cpu_use=[]
    for i in cpu:
        if i>80:
            cpu_use.append(i)

    return cpu_use

In [37]:
paillier_cpu_use_short=shortlist_cpu_usage(cpu_usages_paillier)
paillier_cpu_use_short

[98.3,
 100.1,
 100.5,
 101.2,
 96.8,
 98.3,
 97.2,
 101.3,
 101.5,
 101.7,
 104.0,
 101.8,
 97.4,
 101.3,
 98.2,
 99.9,
 98.1,
 94.4,
 95.9,
 93.9,
 102.1,
 97.1,
 99.5,
 101.5,
 99.2,
 99.6,
 99.1,
 103.2,
 97.6,
 97.1,
 97.8,
 95.1,
 102.2,
 97.8,
 101.8,
 97.5,
 102.8,
 101.6,
 102.2,
 100.9,
 104.4,
 97.3,
 97.9,
 95.3,
 99.3,
 98.7,
 101.1,
 101.0,
 101.2,
 103.5,
 99.2,
 101.5,
 101.3,
 102.7,
 98.3,
 97.8,
 96.3,
 97.6,
 100.8,
 102.2,
 100.7,
 101.7,
 99.8,
 100.6,
 100.0,
 99.5,
 97.8,
 96.8,
 97.8,
 98.4,
 99.2,
 102.2,
 99.0,
 100.9,
 100.0,
 100.7,
 101.0,
 99.7,
 94.0,
 97.5,
 96.3,
 97.1,
 102.8,
 99.7,
 101.3,
 101.9,
 101.1,
 100.3,
 101.3,
 100.3,
 101.5,
 97.1,
 93.3,
 97.1,
 97.4,
 103.2,
 100.6,
 102.2,
 101.0,
 96.8,
 100.8,
 99.9,
 101.3,
 94.9,
 97.1,
 94.4,
 97.2,
 100.9,
 100.2,
 99.1,
 100.8,
 99.7,
 98.9,
 99.9,
 101.3,
 99.6,
 96.5,
 97.9,
 94.1,
 101.5,
 99.6,
 98.5,
 103.3,
 103.3,
 100.2,
 100.7,
 102.2,
 101.1,
 99.4,
 97.4,
 95.2,
 97.5,
 100.3,
 102.6

In [38]:
paillier_cpu_use_short=np.array(paillier_cpu_use_short)

In [39]:
paillier_cpu_use_short.mean()

99.61529073941134

In [40]:
paillier_cpu_use_short.sum()

416292.3

In [41]:
cpu_seconds_for_paillier=paillier_cpu_use_short.sum()/100
cpu_seconds_for_paillier

4162.923

In [42]:
paillier_cpu_use_short.max()

120.6

In [43]:
paillier_cpu_use_short.min()

91.0

In [44]:
len(paillier_cpu_use_short)

4179

In [45]:
cpu_percent_consumption_paillier=(paillier_cpu_use_short.sum()/(len(paillier_cpu_use_short)*200))*100

In [46]:
cpu_percent_consumption_paillier

49.807645369705675

In [47]:
ckks_cpu_use_short=shortlist_cpu_usage(cpu_usages_ckks)
ckks_cpu_use_short

[103.4,
 100.3,
 97.9,
 98.6,
 95.2,
 103.6,
 118.3,
 111.4,
 115.3,
 95.4,
 110.6,
 100.5,
 89.3,
 96.4,
 103.8,
 96.8,
 118.6,
 110.0,
 110.2,
 105.0,
 105.5,
 89.4,
 96.7,
 99.4]

In [48]:
ckks_cpu_use_short=np.array(ckks_cpu_use_short)

In [49]:
ckks_cpu_use_short.mean()

102.98333333333335

In [50]:
ckks_cpu_use_short.sum()

2471.6000000000004

In [51]:
cpu_seconds_for_ckks=ckks_cpu_use_short.sum()/100
cpu_seconds_for_ckks

24.716000000000005

In [52]:
ckks_cpu_use_short.max()

118.6

In [53]:
ckks_cpu_use_short.min()

89.3

In [54]:
len(ckks_cpu_use_short)

24

In [55]:
cpu_percent_consumption_ckks=(ckks_cpu_use_short.sum()/(len(ckks_cpu_use_short)*200))*100
cpu_percent_consumption_ckks

51.49166666666667

In [56]:
joblib.dump((ckks_cpu_use_short.mean(),ckks_cpu_use_short.sum(),cpu_seconds_for_ckks,ckks_cpu_use_short.max(),ckks_cpu_use_short.min(),len(ckks_cpu_use_short),cpu_percent_consumption_ckks),'cpu_util_insights_ckks_1055_21.pkl')

['cpu_util_insights_ckks_1055_21.pkl']

In [57]:
joblib.dump((paillier_cpu_use_short.mean(),paillier_cpu_use_short.sum(),cpu_seconds_for_paillier,paillier_cpu_use_short.max(),paillier_cpu_use_short.min(),len(paillier_cpu_use_short),cpu_percent_consumption_paillier),'cpu_util_insights_paillier_1055_21.pkl')

['cpu_util_insights_paillier_1055_21.pkl']