In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import joblib
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
%matplotlib inline
plt.style.use('dark_background')

In [2]:
weights_paillier,bias_paillier,unenc_preds_paillier,cpu_seconds_paillier,cpu_usages_paillier,train_time_paillier,test_time_paillier=joblib.load('variables_paillier.pkl')

In [3]:
weights_ckks,bias_ckks,unenc_preds_ckks,cpu_seconds_ckks,cpu_usages_ckks,train_time_ckks,test_time_ckks=joblib.load('variables.pkl')

In [4]:
weights_sklearn,bias_sklearn,unenc_preds_sklearn=joblib.load('variables_sklearn.pkl')

In [5]:
y_test=pd.read_csv('y_test3.csv')
y_test=y_test.to_numpy()

In [6]:
y_test=y_test.reshape(-1,)
y_test

array([ 53.  ,  91.  ,  27.  ,  75.  , 126.  ,  49.39,  97.38, 160.  ,
        26.5 ,  91.  ,  50.63,  78.  ,  40.  ,  55.44, 112.  , 130.  ,
        56.  ,  63.5 ,  64.  , 187.  ,  46.5 ,  45.  ,  89.56,  85.  ,
       165.  , 189.  ,  37.97,  83.  ,  71.  ,  65.35,  44.  , 104.  ,
        37.95,  60.  , 113.  ,  45.  ,  64.5 ,  70.  , 107.  , 134.  ,
       100.  ,  44.  , 120.  ,  46.  ,  74.  ,  60.  ,  66.  , 290.  ,
        46.  ,  45.  , 108.  ,  47.65,  70.5 , 119.  ,  38.55,  28.88,
        58.86,  50.  ,  26.  ,  55.  ,  46.  , 300.  ,  86.8 ,  67.77,
        48.  ,  46.  ,  72.  ,  52.  ,  74.  ,  33.06,  75.  ,  48.  ,
        40.  , 140.  , 170.  ,  59.46,  39.9 ,  88.  ,  80.  ,  88.  ,
        30.88,  47.  ,  44.  , 118.  ,  40.  ,  90.  ,  80.  ,  90.  ,
        46.  , 198.  ,  84.  , 100.  ,  53.  ,  90.  , 125.  ,  38.41,
        40.08,  40.54, 400.  ,  54.  , 124.  ,  67.98,  52.85, 118.  ,
        62.  ,  40.54,  37.93, 130.  ,  38.37,  42.54, 199.  , 105.  ,
      

In [7]:
unenc_preds_paillier=np.array(unenc_preds_paillier)
unenc_preds_paillier.shape

(279,)

In [8]:
y_test.shape

(279,)

In [9]:
unenc_preds_ckks=np.array(unenc_preds_ckks)
unenc_preds_ckks=unenc_preds_ckks.reshape(-1,)
unenc_preds_ckks.shape

(279,)

In [10]:
unenc_preds_sklearn=unenc_preds_sklearn.reshape(-1,)
unenc_preds_sklearn.shape

(279,)

### Mean Squared Error:

In [11]:
from sklearn.metrics import mean_squared_error

In [12]:
mse_sklearn=mean_squared_error(unenc_preds_sklearn,y_test)

In [13]:
mse_sklearn

294.6889591175362

In [14]:
mse_ckks=mean_squared_error(unenc_preds_ckks,y_test)
mse_ckks

294.6889462649803

In [15]:
mse_paillier=mean_squared_error(unenc_preds_paillier,y_test)
mse_paillier

294.68895911753316

In [16]:
def calculate_variance(numbers):
    
    if len(numbers) < 2:
        raise ValueError("Variance requires at least two data points.")
    
    mean = sum(numbers) / len(numbers)
    squared_diffs = [(x - mean) ** 2 for x in numbers]
    variance = sum(squared_diffs) / (len(numbers) - 1)
    
    return variance


print("Variance:", calculate_variance(unenc_preds_sklearn))
print("Variance:", calculate_variance(unenc_preds_ckks))
print("Variance:", calculate_variance(unenc_preds_paillier))

Variance: 2503.2632910611005
Variance: 2503.264010268997
Variance: 2503.263291061097


In [17]:
f_statistic,p_value=stats.f_oneway(unenc_preds_sklearn,unenc_preds_ckks,unenc_preds_paillier)

In [18]:
f_statistic,p_value

(6.293557672544196e-12, 0.9999999999937037)

In [19]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference between the values")
else:
    print("There is no significant difference between the values")

There is no significant difference between the values


In [20]:
diff_between_ckks_and_sklearn=abs(unenc_preds_ckks-unenc_preds_sklearn)

In [21]:
diff_between_ckks_and_sklearn[:5]

array([9.64713615e-06, 1.08933505e-05, 4.76859336e-06, 1.15553874e-05,
       1.60722509e-05])

In [22]:
diff_between_paillier_and_sklearn=abs(unenc_preds_paillier-unenc_preds_sklearn)

In [23]:
diff_between_paillier_and_sklearn

array([7.53175300e-13, 7.24753590e-13, 6.85673740e-13, 8.66862138e-13,
       9.80548975e-13, 8.73967565e-13, 1.08002496e-12, 1.05160325e-12,
       7.95807864e-13, 1.02318154e-12, 8.24229573e-13, 9.94759830e-13,
       7.81597009e-13, 1.19371180e-12, 1.03739239e-12, 9.66338121e-13,
       1.17950094e-12, 8.81072992e-13, 1.06581410e-12, 8.24229573e-13,
       7.88702437e-13, 7.03437308e-13, 1.02318154e-12, 1.06581410e-12,
       7.95807864e-13, 7.95807864e-13, 8.66862138e-13, 8.66862138e-13,
       1.02318154e-12, 7.46069873e-13, 8.31335001e-13, 1.06581410e-12,
       8.66862138e-13, 7.24753590e-13, 1.02318154e-12, 9.23705556e-13,
       7.46069873e-13, 8.24229573e-13, 1.03739239e-12, 8.38440428e-13,
       1.06581410e-12, 8.81072992e-13, 1.02318154e-12, 7.53175300e-13,
       7.38964445e-13, 7.81597009e-13, 9.66338121e-13, 1.25055521e-12,
       7.24753590e-13, 1.10844667e-12, 7.24753590e-13, 8.88178420e-13,
       1.02318154e-12, 1.02318154e-12, 8.52651283e-13, 7.74491582e-13,
      

In [24]:
t_statistic,p_value=stats.ttest_ind(diff_between_paillier_and_sklearn,diff_between_ckks_and_sklearn)
t_statistic,p_value

(-30.130371127176314, 5.702999373475052e-119)

In [25]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference between the ckks-sklearn preds and paillier-sklearn preds")
else:
    print("There is no significant difference between the ckks-sklearn preds and paillier-sklearn preds")

There is a significant difference between the ckks-sklearn preds and paillier-sklearn preds


In [26]:
l=len(diff_between_paillier_and_sklearn)

In [27]:
mse_ckks_with_sklearn=sum(diff_between_ckks_and_sklearn**2)/l
mse_ckks_with_sklearn

2.2127719659876843e-10

In [28]:
mse_paillier_with_sklearn=sum(diff_between_paillier_and_sklearn**2)/l
mse_paillier_with_sklearn

8.057644696702487e-25

### training time:

In [29]:
if train_time_ckks<train_time_paillier:
    print("ckks encryption takes less time to train the model")
else:
    print("paillier encryption takes less time to train the model")

ckks encryption takes less time to train the model


In [30]:
train_time_ckks

4.281987905502319

In [31]:
train_time_paillier

225.28963327407837

In [32]:
if test_time_ckks<test_time_paillier:
    print("ckks encrypted data takes less time to test the model")
else:
    print("paillier encrypted data takes less time to train the model")

ckks encrypted data takes less time to test the model


In [33]:
test_time_ckks

3.261003255844116

In [34]:
test_time_paillier

11.212193012237549

In [35]:
joblib.dump(train_time_ckks,'train_time_ckks_1113_5.pkl')
joblib.dump(train_time_paillier,'train_time_paillier_1113_5.pkl')
joblib.dump(test_time_ckks,'test_time_ckks_1113_5.pkl')
joblib.dump(test_time_paillier,'test_time_paillier_1113_5.pkl')

['test_time_paillier_1113_5.pkl']

### CPU % utilization:

In [36]:
def shortlist_cpu_usage(cpu):
    cpu_use=[]
    for i in cpu:
        if i>80:
            cpu_use.append(i)

    return cpu_use

In [37]:
paillier_cpu_use_short=shortlist_cpu_usage(cpu_usages_paillier)
paillier_cpu_use_short

[99.8,
 101.1,
 96.3,
 99.2,
 103.0,
 102.9,
 97.2,
 102.0,
 100.0,
 100.0,
 102.8,
 97.4,
 99.7,
 97.5,
 100.4,
 103.4,
 99.7,
 100.4,
 102.1,
 99.6,
 100.6,
 101.1,
 100.9,
 100.1,
 96.0,
 98.3,
 99.4,
 101.2,
 102.3,
 99.5,
 100.7,
 101.2,
 100.3,
 100.4,
 101.3,
 99.8,
 97.9,
 102.3,
 101.7,
 101.1,
 100.2,
 100.1,
 101.0,
 101.3,
 100.1,
 101.3,
 98.9,
 97.2,
 103.1,
 99.3,
 101.3,
 101.7,
 102.3,
 100.1,
 100.3,
 99.3,
 101.7,
 100.4,
 97.9,
 101.4,
 100.0,
 100.4,
 99.3,
 101.3,
 101.3,
 100.0,
 99.9,
 100.1,
 101.2,
 98.1,
 101.4,
 100.2,
 101.3,
 102.1,
 99.8,
 100.0,
 101.4,
 100.0,
 101.2,
 101.2,
 98.4,
 97.2,
 101.2,
 101.7,
 99.8,
 100.2,
 102.3,
 101.8,
 98.9,
 101.1,
 97.8,
 98.6,
 99.2,
 100.7,
 102.2,
 99.8,
 99.4,
 101.9,
 103.8,
 100.3,
 102.3,
 101.5,
 97.7,
 98.4,
 100.1,
 102.8,
 100.5,
 98.0,
 100.2,
 100.0,
 102.1,
 100.3,
 101.0,
 99.4,
 97.9,
 100.3,
 99.5,
 102.0,
 101.1,
 100.2,
 99.1,
 101.2,
 100.0,
 100.3,
 100.6,
 97.4,
 100.1,
 100.0,
 101.0,
 101.1,
 

In [38]:
paillier_cpu_use_short=np.array(paillier_cpu_use_short)

In [39]:
paillier_cpu_use_short.mean()

100.31697247706421

In [40]:
paillier_cpu_use_short.sum()

21869.1

In [41]:
cpu_seconds_for_paillier=paillier_cpu_use_short.sum()/100
cpu_seconds_for_paillier

218.69099999999997

In [42]:
paillier_cpu_use_short.max()

107.7

In [43]:
paillier_cpu_use_short.min()

94.4

In [44]:
len(paillier_cpu_use_short)

218

In [45]:
cpu_percent_consumption_paillier=(paillier_cpu_use_short.sum()/(len(paillier_cpu_use_short)*200))*100

In [46]:
cpu_percent_consumption_paillier

50.158486238532106

In [47]:
ckks_cpu_use_short=shortlist_cpu_usage(cpu_usages_ckks)
ckks_cpu_use_short

[95.3, 97.3, 96.1]

In [48]:
ckks_cpu_use_short=np.array(ckks_cpu_use_short)

In [49]:
ckks_cpu_use_short.mean()

96.23333333333333

In [50]:
ckks_cpu_use_short.sum()

288.7

In [51]:
cpu_seconds_for_ckks=ckks_cpu_use_short.sum()/100
cpu_seconds_for_ckks

2.887

In [52]:
ckks_cpu_use_short.max()

97.3

In [53]:
ckks_cpu_use_short.min()

95.3

In [54]:
len(ckks_cpu_use_short)

3

In [55]:
cpu_percent_consumption_ckks=(ckks_cpu_use_short.sum()/(len(ckks_cpu_use_short)*200))*100
cpu_percent_consumption_ckks

48.11666666666666

In [56]:
joblib.dump((ckks_cpu_use_short.mean(),ckks_cpu_use_short.sum(),cpu_seconds_for_ckks,ckks_cpu_use_short.max(),ckks_cpu_use_short.min(),len(ckks_cpu_use_short),cpu_percent_consumption_ckks),'cpu_util_insights_ckks_1113_5.pkl')

['cpu_util_insights_ckks_1113_5.pkl']

In [57]:
joblib.dump((paillier_cpu_use_short.mean(),paillier_cpu_use_short.sum(),cpu_seconds_for_paillier,paillier_cpu_use_short.max(),paillier_cpu_use_short.min(),len(paillier_cpu_use_short),cpu_percent_consumption_paillier),'cpu_util_insights_paillier_1113_5.pkl')

['cpu_util_insights_paillier_1113_5.pkl']