In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import joblib
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
%matplotlib inline
plt.style.use('dark_background')

In [2]:
weights_paillier,bias_paillier,unenc_preds_paillier,cpu_seconds_paillier,cpu_usages_paillier,train_time_paillier,test_time_paillier=joblib.load('variables_paillier (1).pkl')

In [3]:
weights_ckks,bias_ckks,unenc_preds_ckks,cpu_seconds_ckks,cpu_usages_ckks,train_time_ckks,test_time_ckks=joblib.load('variables.pkl')

In [4]:
weights_sklearn,bias_sklearn,unenc_preds_sklearn=joblib.load('variables_sklearn.pkl')

In [5]:
y_test=pd.read_csv('y_test2.csv')
y_test=y_test.to_numpy()

In [6]:
y_test=y_test.reshape(-1,)
y_test

array([211.  ,  55.  , 125.  , 130.  ,  85.  , 125.  ,  55.  , 190.  ,
        54.  ,  65.  , 146.  ,  78.57,  50.  ,  22.  , 400.  , 130.  ,
       143.  , 126.  , 135.  , 100.  ,  75.  ,  71.  , 115.  ,  74.03,
        40.54,  91.  ,  78.  , 360.  ,  69.5 , 138.  , 110.  ,  52.7 ,
        57.  , 250.  ,  58.  ,  60.  ,  95.05, 300.  ,  96.17,  65.  ,
        63.43,  88.  , 107.  , 188.  ,  58.  , 130.  ,  68.  ,  47.  ,
       160.  ,  55.  ,  43.  ,  45.  ,  38.55,  66.  ,  35.  ,  88.  ,
       185.  ,  48.  ,  40.  ,  70.93,  96.9 ,  46.  ,  46.  ,  66.  ,
       163.  ,  90.  ,  54.1 ,  53.76, 116.  ,  41.  ,  50.  ,  45.  ,
        40.  ,  93.  ,  65.  ,  65.75, 140.  ,  70.  ,  46.  ,  89.  ,
        56.1 ,  46.  ,  79.  ,  78.  ,  64.86,  57.6 ,  55.  , 175.  ,
       200.  ,  90.  ,  44.17,  95.  ,  98.  ,  77.5 , 130.  ,  61.  ,
        45.  , 104.  ,  44.  , 140.  , 116.  , 100.  , 270.  , 105.  ,
       115.  ,  40.17, 190.  ,  62.  ,  45.  ,  88.  , 128.  , 180.  ,
      

In [7]:
unenc_preds_paillier=np.array(unenc_preds_paillier)
unenc_preds_paillier.shape

(158,)

In [8]:
y_test.shape

(158,)

In [9]:
unenc_preds_ckks=np.array(unenc_preds_ckks)
unenc_preds_ckks=unenc_preds_ckks.reshape(-1,)
unenc_preds_ckks.shape

(158,)

In [10]:
unenc_preds_sklearn=unenc_preds_sklearn.reshape(-1,)
unenc_preds_sklearn.shape

(158,)

### Mean Squared Error:

In [11]:
from sklearn.metrics import mean_squared_error

In [12]:
mse_sklearn=mean_squared_error(unenc_preds_sklearn,y_test)

In [13]:
mse_sklearn

361.2599630692902

In [14]:
mse_ckks=mean_squared_error(unenc_preds_ckks,y_test)
mse_ckks

361.2597424815084

In [15]:
mse_paillier=mean_squared_error(unenc_preds_paillier,y_test)
mse_paillier

361.2599630692942

In [16]:
def calculate_variance(numbers):
    
    if len(numbers) < 2:
        raise ValueError("Variance requires at least two data points.")
    
    mean = sum(numbers) / len(numbers)
    squared_diffs = [(x - mean) ** 2 for x in numbers]
    variance = sum(squared_diffs) / (len(numbers) - 1)
    
    return variance


print("Variance:", calculate_variance(unenc_preds_sklearn))
print("Variance:", calculate_variance(unenc_preds_ckks))
print("Variance:", calculate_variance(unenc_preds_paillier))

Variance: 3448.8267346938233
Variance: 3448.827904422402
Variance: 3448.826734693775


In [17]:
f_statistic,p_value=stats.f_oneway(unenc_preds_sklearn,unenc_preds_ckks,unenc_preds_paillier)

In [18]:
f_statistic,p_value

(3.574427945034589e-12, 0.9999999999964181)

In [19]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference between the values")
else:
    print("There is no significant difference between the values")

There is no significant difference between the values


In [20]:
diff_between_ckks_and_sklearn=abs(unenc_preds_ckks-unenc_preds_sklearn)

In [21]:
diff_between_ckks_and_sklearn[:5]

array([3.18698982e-05, 1.07947681e-05, 2.48714944e-05, 1.92645674e-05,
       1.31505434e-05])

In [22]:
diff_between_paillier_and_sklearn=abs(unenc_preds_paillier-unenc_preds_sklearn)

In [23]:
diff_between_paillier_and_sklearn

array([3.12638804e-13, 5.54223334e-13, 2.55795385e-13, 2.84217094e-14,
       8.52651283e-14, 2.27373675e-13, 5.89750471e-13, 3.41060513e-13,
       4.26325641e-13, 4.40536496e-13, 1.70530257e-13, 1.42108547e-13,
       9.94759830e-13, 1.01252340e-12, 9.09494702e-13, 2.84217094e-14,
       4.26325641e-13, 2.55795385e-13, 0.00000000e+00, 1.42108547e-14,
       3.55271368e-13, 1.84741111e-13, 7.10542736e-14, 5.25801624e-13,
       5.11590770e-13, 1.27897692e-13, 1.56319402e-13, 7.38964445e-13,
       4.68958206e-13, 1.42108547e-14, 2.98427949e-13, 6.53699317e-13,
       5.54223334e-13, 8.24229573e-13, 1.84741111e-13, 3.90798505e-13,
       5.68434189e-13, 7.38964445e-13, 5.54223334e-13, 3.55271368e-13,
       5.68434189e-14, 7.10542736e-14, 9.94759830e-14, 1.42108547e-13,
       3.97903932e-13, 2.84217094e-14, 5.18696197e-13, 3.90798505e-13,
       7.10542736e-13, 0.00000000e+00, 4.12114787e-13, 5.40012479e-13,
       5.11590770e-13, 5.40012479e-13, 8.77520279e-13, 7.10542736e-14,
      

In [24]:
t_statistic,p_value=stats.ttest_ind(diff_between_paillier_and_sklearn,diff_between_ckks_and_sklearn)
t_statistic,p_value

(-19.122339235304864, 1.3624867568445717e-54)

In [25]:
alpha = 0.05
if p_value < alpha:
    print("There is a significant difference between the ckks-sklearn preds and paillier-sklearn preds")
else:
    print("There is no significant difference between the ckks-sklearn preds and paillier-sklearn preds")

There is a significant difference between the ckks-sklearn preds and paillier-sklearn preds


In [26]:
l=len(diff_between_paillier_and_sklearn)

In [27]:
mse_ckks_with_sklearn=sum(diff_between_ckks_and_sklearn**2)/l
mse_ckks_with_sklearn

3.362528493788875e-10

In [28]:
mse_paillier_with_sklearn=sum(diff_between_paillier_and_sklearn**2)/l
mse_paillier_with_sklearn

2.2526572211356113e-25

### training time:

In [29]:
if train_time_ckks<train_time_paillier:
    print("ckks encryption takes less time to train the model")
else:
    print("paillier encryption takes less time to train the model")

ckks encryption takes less time to train the model


In [30]:
if test_time_ckks<test_time_paillier:
    print("ckks encrypted data takes less time to test the model")
else:
    print("paillier encrypted data takes less time to train the model")

ckks encrypted data takes less time to test the model


In [31]:
train_time_ckks

4.0029613971710205

In [32]:
train_time_paillier

184.30677795410156

In [33]:
test_time_ckks

2.109273910522461

In [34]:
test_time_paillier

9.071547269821167

In [35]:
joblib.dump(train_time_ckks,'train_time_ckks_631_5.pkl')
joblib.dump(train_time_paillier,'train_time_paillier_631_5.pkl')
joblib.dump(test_time_ckks,'test_time_ckks_631_5.pkl')
joblib.dump(test_time_paillier,'test_time_paillier_631_5.pkl')

['test_time_paillier_631_5.pkl']

### CPU % utilization:

In [36]:
def shortlist_cpu_usage(cpu):
    cpu_use=[]
    for i in cpu:
        if i>80:
            cpu_use.append(i)

    return cpu_use

In [37]:
paillier_cpu_use_short=shortlist_cpu_usage(cpu_usages_paillier)
paillier_cpu_use_short

[99.1,
 99.7,
 98.1,
 96.4,
 96.7,
 97.0,
 102.0,
 100.2,
 101.5,
 101.0,
 99.8,
 100.0,
 101.7,
 99.5,
 100.1,
 97.3,
 97.9,
 95.4,
 96.3,
 103.4,
 101.4,
 98.1,
 99.8,
 97.1,
 100.9,
 100.9,
 103.1,
 101.3,
 98.9,
 95.8,
 97.3,
 95.4,
 99.0,
 98.6,
 99.7,
 100.3,
 103.2,
 99.4,
 99.7,
 98.1,
 96.9,
 99.5,
 97.4,
 96.4,
 97.9,
 99.6,
 99.6,
 99.1,
 99.6,
 100.7,
 96.6,
 101.3,
 104.3,
 99.4,
 96.7,
 94.7,
 96.6,
 98.9,
 99.5,
 101.9,
 100.8,
 102.3,
 100.3,
 102.4,
 100.2,
 102.8,
 99.6,
 99.3,
 96.7,
 95.9,
 99.4,
 99.4,
 99.7,
 100.1,
 101.9,
 100.4,
 101.4,
 102.6,
 100.0,
 101.1,
 97.5,
 98.3,
 97.0,
 100.0,
 99.0,
 100.5,
 101.1,
 101.9,
 101.0,
 101.4,
 103.2,
 100.3,
 100.9,
 97.3,
 95.8,
 95.8,
 101.3,
 98.6,
 99.9,
 99.4,
 100.1,
 101.5,
 101.6,
 102.8,
 101.4,
 99.1,
 96.1,
 96.9,
 96.3,
 98.3,
 104.0,
 100.5,
 100.7,
 103.3,
 100.4,
 100.2,
 102.3,
 101.0,
 100.1,
 95.4,
 96.4,
 96.3,
 101.0,
 98.6,
 97.2,
 101.8,
 102.2,
 99.3,
 102.0,
 101.1,
 99.8,
 98.8,
 97.2,
 96.4,
 

In [38]:
paillier_cpu_use_short=np.array(paillier_cpu_use_short)

In [39]:
paillier_cpu_use_short.mean()

99.68192090395479

In [40]:
paillier_cpu_use_short.sum()

17643.699999999997

In [41]:
cpu_seconds_for_paillier=paillier_cpu_use_short.sum()/100
cpu_seconds_for_paillier

176.43699999999998

In [42]:
paillier_cpu_use_short.max()

114.4

In [43]:
paillier_cpu_use_short.min()

94.7

In [44]:
len(paillier_cpu_use_short)

177

In [45]:
cpu_percent_consumption_paillier=(paillier_cpu_use_short.sum()/(len(paillier_cpu_use_short)*200))*100

In [46]:
cpu_percent_consumption_paillier

49.840960451977395

In [47]:
ckks_cpu_use_short=shortlist_cpu_usage(cpu_usages_ckks)
ckks_cpu_use_short

[99.7, 99.4, 94.9]

In [48]:
ckks_cpu_use_short=np.array(ckks_cpu_use_short)

In [49]:
ckks_cpu_use_short.mean()

98.0

In [50]:
ckks_cpu_use_short.sum()

294.0

In [51]:
cpu_seconds_for_ckks=ckks_cpu_use_short.sum()/100
cpu_seconds_for_ckks

2.94

In [52]:
ckks_cpu_use_short.max()

99.7

In [53]:
ckks_cpu_use_short.min()

94.9

In [54]:
len(ckks_cpu_use_short)

3

In [55]:
cpu_percent_consumption_ckks=(ckks_cpu_use_short.sum()/(len(ckks_cpu_use_short)*200))*100
cpu_percent_consumption_ckks

49.0

In [56]:
joblib.dump((ckks_cpu_use_short.mean(),ckks_cpu_use_short.sum(),cpu_seconds_for_ckks,ckks_cpu_use_short.max(),ckks_cpu_use_short.min(),len(ckks_cpu_use_short),cpu_percent_consumption_ckks),'cpu_util_insights_ckks_631_5.pkl')

['cpu_util_insights_ckks_631_5.pkl']

In [57]:
joblib.dump((paillier_cpu_use_short.mean(),paillier_cpu_use_short.sum(),cpu_seconds_for_paillier,paillier_cpu_use_short.max(),paillier_cpu_use_short.min(),len(paillier_cpu_use_short),cpu_percent_consumption_paillier),'cpu_util_insights_paillier_631_5.pkl')

['cpu_util_insights_paillier_631_5.pkl']